// ============================================
// Sample Data for Development
// Used when Supabase is not connected
// ============================================

import type { Product, Category } from "@/types/database";

export const sampleCategories: Category[] = [
  {
    id: "c1000000-0000-0000-0000-000000000001",
    name: "Posters",
    slug: "posters",
    description: "Premium quality art posters that transform your walls into gallery-worthy spaces.",
    image_url: null,
    parent_id: null,
    sort_order: 1,
    is_active: true,
    seo_title: "Premium Art Posters | PrintMacha",
    seo_description: "Shop premium quality art posters",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-0000-0000-000000000002",
    name: "3D Textured Posters",
    slug: "3d-textured-posters",
    description: "Stunning 3D textured wall art with depth and dimension you can feel.",
    image_url: null,
    parent_id: null,
    sort_order: 2,
    is_active: true,
    seo_title: "3D Textured Wall Art | PrintMacha",
    seo_description: "Shop 3D textured wall art",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-0000-0000-000000000003",
    name: "F1 Collection",
    slug: "f1-collection",
    description: "Formula 1 inspired 3D printed art and collectibles for motorsport enthusiasts.",
    image_url: null,
    parent_id: null,
    sort_order: 3,
    is_active: true,
    seo_title: "F1 Collection | PrintMacha",
    seo_description: "Shop F1 inspired 3D printed art",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-0000-0000-000000000004",
    name: "Desk Accessories",
    slug: "desk-accessories",
    description: "Thoughtfully designed 3D printed accessories that elevate your workspace.",
    image_url: null,
    parent_id: null,
    sort_order: 4,
    is_active: true,
    seo_title: "Desk Accessories | PrintMacha",
    seo_description: "Shop 3D printed desk accessories",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const sampleProducts: Product[] = [
  {
    id: "p1000000-0000-0000-0000-000000000001",
    title: "Midnight Bloom Abstract",
    slug: "midnight-bloom-abstract",
    short_description: "A captivating abstract poster featuring dark florals against a moody backdrop.",
    long_description: "This premium art poster brings the mystery of midnight gardens into your space. Printed on 300gsm museum-quality art paper with archival inks.",
    category_id: "c1000000-0000-0000-0000-000000000001",
    subcategory_id: null,
    tags: ["abstract", "floral", "dark", "premium"],
    sku: "PM-POST-001",
    base_price: 599,
    sale_price: 449,
    compare_at_price: 599,
    stock_quantity: 25,
    stock_status: "in_stock",
    featured_image: null,
    is_featured: true,
    is_new_arrival: false,
    is_best_seller: true,
    is_published: true,
    material: "300gsm Art Paper",
    size: "A3 (297×420mm)",
    color: "Multi",
    finish: "Matte",
    delivery_estimate: "5-7 business days",
    return_eligible: true,
    seo_title: null,
    seo_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: sampleCategories[0],
  },
  {
    id: "p1000000-0000-0000-0000-000000000002",
    title: "Geometric Sunrise",
    slug: "geometric-sunrise",
    short_description: "Warm geometric patterns that bring energy and light to any room.",
    long_description: "Inspired by the golden hour, this geometric poster combines warm oranges, yellows, and soft pinks.",
    category_id: "c1000000-0000-0000-0000-000000000001",
    subcategory_id: null,
    tags: ["geometric", "warm", "abstract", "modern"],
    sku: "PM-POST-002",
    base_price: 599,
    sale_price: null,
    compare_at_price: null,
    stock_quantity: 30,
    stock_status: "in_stock",
    featured_image: null,
    is_featured: false,
    is_new_arrival: true,
    is_best_seller: false,
    is_published: true,
    material: "300gsm Art Paper",
    size: "A3 (297×420mm)",
    color: "Multi",
    finish: "Matte",
    delivery_estimate: "5-7 business days",
    return_eligible: true,
    seo_title: null,
    seo_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: sampleCategories[0],
  },
  {
    id: "p1000000-0000-0000-0000-000000000005",
    title: "Wave Form Texture Panel",
    slug: "wave-form-texture-panel",
    short_description: "Mesmerizing 3D printed wave pattern that creates stunning shadow play.",
    long_description: "Our signature Wave Form panel brings walls to life with its undulating 3D texture.",
    category_id: "c1000000-0000-0000-0000-000000000002",
    subcategory_id: null,
    tags: ["3d-texture", "wave", "wall-art", "premium"],
    sku: "PM-3DT-001",
    base_price: 2499,
    sale_price: 1999,
    compare_at_price: 2499,
    stock_quantity: 10,
    stock_status: "in_stock",
    featured_image: null,
    is_featured: true,
    is_new_arrival: false,
    is_best_seller: true,
    is_published: true,
    material: "PLA Biodegradable",
    size: "12×16 inches",
    color: "Warm White",
    finish: "Matte 3D Textured",
    delivery_estimate: "7-10 business days",
    return_eligible: true,
    seo_title: null,
    seo_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: sampleCategories[1],
  },
  {
    id: "p1000000-0000-0000-0000-000000000006",
    title: "Mountain Ridge Relief",
    slug: "mountain-ridge-relief",
    short_description: "3D topographic mountain art with real dimensional depth.",
    long_description: "Experience the majesty of mountain ranges in three dimensions.",
    category_id: "c1000000-0000-0000-0000-000000000002",
    subcategory_id: null,
    tags: ["3d-texture", "mountain", "topographic", "nature"],
    sku: "PM-3DT-002",
    base_price: 2999,
    sale_price: null,
    compare_at_price: null,
    stock_quantity: 8,
    stock_status: "in_stock",
    featured_image: null,
    is_featured: false,
    is_new_arrival: true,
    is_best_seller: true,
    is_published: true,
    material: "PLA Biodegradable",
    size: "14×18 inches",
    color: "Natural White",
    finish: "Matte 3D Textured",
    delivery_estimate: "7-10 business days",
    return_eligible: true,
    seo_title: null,
    seo_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: sampleCategories[1],
  },
  {
    id: "p1000000-0000-0000-0000-000000000008",
    title: "F1 Circuit Layout - Monaco",
    slug: "f1-circuit-monaco",
    short_description: "3D printed Monaco GP circuit layout wall art - a must for F1 fans.",
    long_description: "Celebrate the most glamorous race on the F1 calendar.",
    category_id: "c1000000-0000-0000-0000-000000000003",
    subcategory_id: null,
    tags: ["f1", "formula-1", "monaco", "circuit", "racing"],
    sku: "PM-F1-001",
    base_price: 3499,
    sale_price: 2899,
    compare_at_price: 3499,
    stock_quantity: 8,
    stock_status: "in_stock",
    featured_image: null,
    is_featured: true,
    is_new_arrival: false,
    is_best_seller: true,
    is_published: true,
    material: "PLA Premium",
    size: "18×14 inches",
    color: "Red/White",
    finish: "Satin 3D Printed",
    delivery_estimate: "7-10 business days",
    return_eligible: true,
    seo_title: null,
    seo_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: sampleCategories[2],
  },
  {
    id: "p1000000-0000-0000-0000-000000000010",
    title: "F1 Car Silhouette Stand",
    slug: "f1-car-silhouette-stand",
    short_description: "Sleek F1 car silhouette desk piece - a miniature icon for your desk.",
    long_description: "A beautifully crafted F1 car silhouette desk piece.",
    category_id: "c1000000-0000-0000-0000-000000000003",
    subcategory_id: null,
    tags: ["f1", "formula-1", "car", "desk", "gift"],
    sku: "PM-F1-003",
    base_price: 899,
    sale_price: 699,
    compare_at_price: 899,
    stock_quantity: 20,
    stock_status: "in_stock",
    featured_image: null,
    is_featured: false,
    is_new_arrival: false,
    is_best_seller: true,
    is_published: true,
    material: "PLA Premium",
    size: "8×3 inches",
    color: "Black",
    finish: "Satin 3D Printed",
    delivery_estimate: "5-7 business days",
    return_eligible: true,
    seo_title: null,
    seo_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: sampleCategories[2],
  },
  {
    id: "p1000000-0000-0000-0000-000000000011",
    title: "Geodesic Pen Holder",
    slug: "geodesic-pen-holder",
    short_description: "Striking geodesic design pen holder that turns organization into art.",
    long_description: "Transform your desk with this architecturally inspired geodesic pen holder.",
    category_id: "c1000000-0000-0000-0000-000000000004",
    subcategory_id: null,
    tags: ["desk", "pen-holder", "geometric", "organizer"],
    sku: "PM-DESK-001",
    base_price: 699,
    sale_price: 549,
    compare_at_price: 699,
    stock_quantity: 30,
    stock_status: "in_stock",
    featured_image: null,
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_published: true,
    material: "PLA Biodegradable",
    size: "4×4×4 inches",
    color: "Terracotta Orange",
    finish: "Matte",
    delivery_estimate: "5-7 business days",
    return_eligible: true,
    seo_title: null,
    seo_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: sampleCategories[3],
  },
  {
    id: "p1000000-0000-0000-0000-000000000014",
    title: "Laptop Stand - Arc",
    slug: "laptop-stand-arc",
    short_description: "Premium ergonomic laptop stand with a clean arc design.",
    long_description: "Elevate your work setup with this premium 3D printed laptop stand.",
    category_id: "c1000000-0000-0000-0000-000000000004",
    subcategory_id: null,
    tags: ["desk", "laptop", "stand", "ergonomic", "premium"],
    sku: "PM-DESK-004",
    base_price: 1499,
    sale_price: null,
    compare_at_price: null,
    stock_quantity: 12,
    stock_status: "in_stock",
    featured_image: null,
    is_featured: true,
    is_new_arrival: false,
    is_best_seller: false,
    is_published: true,
    material: "PLA Biodegradable",
    size: "10×8×4 inches",
    color: "Warm White",
    finish: "Matte",
    delivery_estimate: "7-10 business days",
    return_eligible: true,
    seo_title: null,
    seo_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: sampleCategories[3],
  },
];

export const sampleReviews = [
  { id: "1", reviewer_name: "Ananya S.", rating: 5, title: "Absolutely stunning", body: "The print quality is exceptional. Colors are even more vibrant in person!", product_title: "Midnight Bloom Abstract" },
  { id: "2", reviewer_name: "Priya K.", rating: 5, title: "Unique and beautiful", body: "Nothing like this available anywhere else! The 3D texture is mesmerizing.", product_title: "Wave Form Texture Panel" },
  { id: "3", reviewer_name: "Arjun D.", rating: 5, title: "F1 fans must have this!", body: "The circuit detail is incredible and the team colors are spot on.", product_title: "F1 Circuit Layout - Monaco" },
  { id: "4", reviewer_name: "Dev P.", rating: 5, title: "Desk upgrade complete", body: "This pen holder gets compliments every time someone sees my desk.", product_title: "Geodesic Pen Holder" },
  { id: "5", reviewer_name: "Kavita N.", rating: 5, title: "Solid and stylish", body: "Looks premium, feels solid, works exactly as expected.", product_title: "Laptop Stand - Arc" },
];
